name: e_file
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_staggered_grid_view: ^0.6.2
  toggle_switch: ^2.0.1
  flip_card: ^0.6.0
  percent_indicator: ^4.2.2
  font_awesome_flutter: ^10.1.0
  path_provider: ^2.0.11
  disk_space: ^0.2.1
  permission_handler: ^10.0.0
  units_converter: ^2.0.1
  auto_size_text: ^3.0.0
  storage_info: ^0.0.1
  external_path: ^1.0.3
  file: ^6.1.4
  path: ^1.8.2
  flutter_native_splash: ^2.2.9
  animated_toggle_switch: ^0.5.2
  floating_action_bubble: ^1.1.4
  dropdown_button2: ^1.8.1
  flutter_isolate: ^2.0.2
  flutter_advanced_switch: ^3.0.1
  dynamic_color: ^1.5.4
  ffi: ^2.0.1
  random_string: ^2.3.1
  flutter_switch: ^0.3.2
  photo_view: ^0.14.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

