name: testapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^10.0.0
  path_provider: ^2.0.11
  back_button_interceptor: ^6.0.1
  android_package_manager: ^0.1.0
  auto_size_text: ^3.0.0
  floating_action_bubble: 1.1.4
  telegram_client: ^0.3.55
  ffi: ^2.0.1
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  ffigen: ^7.0.0
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true


ffigen:
  output: 'lib/generated_bindings.dart'
  headers:
    entry-points:
      - 'bindings.h'
