name: tfile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.5.4
  floating_action_bubble: 1.1.4
  ffi: ^2.0.1
  http: ^0.13.5
  path: ^1.8.2
  path_provider: ^2.0.11
  auto_size_text: ^3.0.0
  permission_handler: ^10.1.0
  file_picker: ^5.2.0+1
  intl_phone_field: ^3.1.0
  introduction_screen: 3.0.2
  lottie: ^1.4.3
  pin_code_fields: ^7.4.0
  rounded_loading_button: ^2.1.0
  otp_text_field: ^1.1.3
  get_storage: ^2.0.3
  get: ^4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.2.1
  ffigen: ^6.1.2
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/cloud_upload.json
    - assets/lottie/github_logo.json
    - assets/lottie/secure.json
    - assets/lottie/telegram.json
    - assets/lottie/password.json
    - assets/lottie/new_user.json
    - assets/lottie/telegram_sms.json
    - assets/lottie/telegram_sms1.json
    - assets/lottie/telegram_mail.json
  uses-material-design: true

ffigen: 
  output: lib/app/tdLibJson/tdlib_native.dart
  name: 'TDLibNative'
  description: 'Bindings for TdLibJson'
  headers: 
    entry-points: 
      - tdlibexport.h

