name: Build and Release

on: [push]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-22.04
    steps:
      - name: clone repo
        uses: actions/checkout@v1
      - name: setup flutter
        run: sudo snap install flutter --classic
      - name: flutter version
        run: flutter doctor
      - name: accecpt licences
        run:  yes | flutter doctor --android-licenses
      - name: build APK
        run: flutter build apk --target-platform=android-arm64
      - name: Send apk
        run: |
          curl -F document=@"build/app/outputs/flutter-apk/app-release.apk" https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument?chat_id=${{ secrets.TELEGRAM_TO }}
