name: Build and Release

on: [push]

jobs:
  build:
    strategy:
      matrix:
        variants:
          - type: Debug
            command: --debug
          - type: Split abi
            command: --split-per-abi
    name: Build ${{ matrix.type }} APK
    runs-on: ubuntu-22.04
    steps:
      - name: clone repo
        uses: actions/checkout@v1
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            /opt/hostedtoolcache/flutter
            build
          key: ${{ runner.OS }}-flutter-install-cache
      - uses: subosito/flutter-action@v2
        with:
         channel: 'stable'
      - name: build ${{ matrix.type }} APK
        run: flutter build apk ${{ matrix.command }}
      - name: Send apk
        run: |
          curl -F document=@"build/app/outputs/flutter-apk/app-release.apk" https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument?chat_id=${{ secrets.TELEGRAM_TO }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%Y%m%d%H%M)"
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: EFile-${{ steps.date.outputs.date }}
          RELEASE_NAME: EFile-${{ steps.date.outputs.date }}
      - name: Upload To release 
        uses: softprops/action-gh-release@v1
        with:
          tag_name: EFile-${{ steps.date.outputs.date }}
          files: build/app/outputs/flutter-apk/*
