name: Build and Release

on: [push]

jobs:
  build:
    strategy:
      matrix:
        variants:
          - type: Debug
            command: --debug
          - type: Split abi
            command: --split-per-abi
    name: Build ${{ matrix.type }} APK
    runs-on: ubuntu-22.04
    steps:
      - name: clone repo
        uses: actions/checkout@v1
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            /opt/hostedtoolcache/flutter
            build
          key: ${{ runner.OS }}-flutter-install-cache
      - uses: subosito/flutter-action@v2
        with:
         channel: 'stable'
      - name: build ${{ matrix.type }} APK
        run: flutter build apk ${{ matrix.command }}
      - name: Send apk
        run: |
          curl -F document=@"build/app/outputs/flutter-apk/app-release.apk" https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument?chat_id=${{ secrets.TELEGRAM_TO }}
